# Generated by Django 2.0.5 on 2018-05-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vacanses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanse',
            name='actual_news',
        ),
    ]
